### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by watchakorn-18k** [JoeSzymkowiczFiveM/qb-vehiclepush#2]
![image](https://user-images.githubusercontent.com/74919942/159097622-ad55b40d-4d99-4dee-8009-73759f35330b.png)

**Comment by JoeSzymkowiczFiveM** [comment]
Ha, this script hasnt been updated in ages. Yeah, the core object import needs to be updated, among other things. I will update this specific error now, and think about further enhancements another time. I'm torn if I really want to continue to maintain it like this, because resources like qtarget are generally seen at the future; not floating 3dtext and IsControlJustPressed.

**Comment by JoeSzymkowiczFiveM** [comment]
Fixed with latest push. Thank you.
